name: master

on:
  push:
    branches:
      - master

jobs:
  job:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: cache ivy
      uses: actions/cache@v1
      env:
        cache-name: cache-ivy
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: lint
      run: |
        sbt scalastyle

    - name: test
      run: |
        sbt "clean; coverage; common/test; cstrike/test; scenario/test; test"
        sbt coverageReport

    - name: assembly
      run: sbt "clean; set test in assembly := {}; assembly"

    - name: deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/scala-2.13/playcs-assembly-0.1.jar
        remote: /tmp/app.jar
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}

    - name: update app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cp /tmp/app.jar ~/playcs/app.jar
          sudo systemctl restart playcs

    - name: inform command
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.INFORM_CHAT_ID }}
        token: ${{ secrets.TG_BOT_API_TOKEN }}
        message: |
          New release is deployed 🚀
          Commit SHA = ${{ github.sha }}
